ezpublish:
    # HttpCache settings, By default 'local' (Symfony HttpCache Proxezpay), by setting it to 'http' you can point it to Varnish
    http_cache:
        purge_type: '%purge_type%'

    # Repositories configuration, setup default repository to support solr if enabled
    repositories:
        default:
            storage: ~
            search:
                engine: "%search_engine%"
                connection: default

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list: [site, site2]
        groups:
            site_group: [site, site2]
        default_siteaccess: site
        match:
            URIElement: 1

    # System settings, grouped by siteaccess and/or siteaccess group
    system:
        site_group:
            # Pool to use for cache, needs to be different per repository (database).
            cache_pool_name: '%cache_pool%'
            # These reflect the current installers, complete installation before you change them. For changing var_dir
            # it is recommended to install clean, then change setting before you start adding binary content, otherwise you'll
            # need to manually modify your database data to reflect this to avoid exceptions.
            var_dir: var/site
            # System languages. Note that by default, content, content types, and other data are in eng-GB locale,
            # so removing eng-GB from this list may lead to errors or content not being shown, unless you change
            # all eng-GB data to other locales first.
            languages: [eng-GB]
            # HttpCache purge server(s) setting, eg Varnish, for when ezpublish.http_cache.purge_type is set to 'http'.
            http_cache:
                purge_servers: ["%purge_server%"]
            content_view:
                full:
                    root_folder:
                        controller: "ez_query:contentQueryAction"
                        template: "@ezdesign/full/welcome.html.twig"
                        params:
                            query:
                                query_type: 'SectionChildren'
                                parameters:
                                    subtree: "@=location.pathString"
                                    type: ['ride']
                                assign_results_to: 'children'
                        match:
                            Id\Location: 2
                    full_ride:
                        controller: "ez_query:contentQueryAction"
                        template: "full/ride.html.twig"
                        match:
                            Identifier\ContentType: "ride"
                        params:
                            query:
                                query_type: 'SectionChildren'
                                parameters:
                                    subtree: "@=location.pathString"
                                    type: ['poi']
                                assign_results_to: 'pois'
                            metadata:
                                provider: metadata_provider
                                options:
                                    use_author_field: true

                line:
                    poi_line:
                        template: "line/point_of_interest.html.twig"
                        match:
                            Identifier\ContentType: "poi"
                        params:
                            metadata:
                                provider: metadata_provider
        site:
            design: my_design1
        site2:
            design: my_design2

ezdesign:
    design_list:
        # my_design will be composed of "theme1" and "theme2"
        # "theme1" will be the first tried. If the template cannot be found in "theme1", "theme2" will be tried out, and then default app/Resources/views folder.
        my_design1: [corporate]
        my_design2: [my_external_theme, site2, corporate]
    templates_theme_paths:
        my_external_theme:
            - '%kernel.root_dir%/../vendor/ezsystems/platform-ui-bundle/Resources/views'

assetic:
    assets:
        corporate_css:
            inputs:
                - "assets/themes/corporate/css/bootstrap.min.css"
                - "assets/themes/corporate/css/bootstrap-theme.css"
                - "assets/themes/corporate/css/normalize.css"

ez_core_extra:
    system:
        site:
            twig_globals:
                website_title: My Summer Camp Site 1
        site2:
            twig_globals:
                website_title: My Summer Camp Site 2